### ISSUE TITLE
Test Code

### ISSUE THREAD

**Issue by ksl1231** [dasongli1/Learning_degradation#1]
Thank you for your excellent work！

could you release the code mentioned in the paper

>  For testing, we slice the whole image into several 256 × 256 patches and test all patches to report the results of HINet [3], MPRNet-patch256 [47] and our method. 

I didn't find the relevant code, thank you!

**Comment by dasongli1** [comment]
The code of slicing the whole image is in the [grid function](https://github.com/dasongli1/Learning_degradation/blob/main/basicsr/models/image_restoration_model.py#L141) in image_restoration_model.py. Testing code will call the grid function and test each patch.
