### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by Ideal-Bushgorman** [dasongli1/Learning_degradation#7]
After reading your paper and codes, I'm still not sure about the training process. According to my understanding, the first step is training version2'(Training version 2's Learning degradation in joint training of reblurring and deblurring). Then  freeze the weights of well-trained encoder E and use training version1 to train the deblurring generator. Is this right？

**Comment by Ideal-Bushgorman** [comment]
according to the code, there is only a debluring branch in the part of training version 1

**Comment by dasongli1** [comment]
I think your understanding is correct. 

The first step is version 2's Learning degradation in joint training of reblurring and deblurring. And this step can achieve degradation learning, degradation interpolation and degradation decoupleness. 
The second step is to train the deblurring generator only to remove the effect of the whole complicated framework for fair comparisons of deblurring. Moreover, for further applications of other related tasks, training deblurring with the pre-trained degradation is more flexible and efficient. 

We release the code of the joint training (first step) in version 2 due to the higher GPU memory in version 1. The encoder of version 2 requires less computational cost than version 1.
The second step of training deblurring is same for version 1 and version 2.

**Comment by Ideal-Bushgorman** [comment]
Since I'm studying image deblurring, I'm want to reproduce your experiments. I would be appreciate it if you can help me make clear of some details.
Here are some of my inferences：1. As you have mentioned, Version 1 need high GPU memory. According to your code, I think the reason is that the deblurring branch in version 1 is more complicated because its framwork is similar to HINet which has two stages and the network is simpler in Version2's(Training version 2's Learning degradation in joint training of reblurring and deblurring).

2. It seems the code just saved the whole network. If so, how can I get the subnetworks(self.prior_upsampling = prior_upsampling(),self.net_prior = ConvEncoder()) . The second one is about Enconder, the first one is to upsample the features generated by encoder.
3. In fig.2 of the paper, the network uses SAM module to integrate features, but in the code, the network uses SPADEResnetBlock to integrate features. (Class HINet, self.ad1_list.append(SPADEResnetBlock((2**i) * wf, (2**i) * wf, norm_G, label_nc=(2**i) * wf))). It confused me a lot.
4. What type of GPU do you use and how long have you been training



19121922&nbsp;李想
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dasongli1/Learning_degradation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月24日(星期六) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dasongli1/Learning_degradation] About training (Issue #7)





 
I think your understanding is correct.
 
The first step is version 2's Learning degradation in joint training of reblurring and deblurring. And this step can achieve degradation learning, degradation interpolation and degradation decoupleness.
 The second step is to train the deblurring generator only to remove the effect of the whole complicated framework for fair comparisons of deblurring. Moreover, for further applications of other related tasks, training deblurring with the pre-trained degradation is more flexible and efficient.
 
We release the code of the joint training (first step) in version 2 due to the higher GPU memory in version 1. The encoder of version 2 requires less computational cost than version 1.
 The second step of training deblurring is same for version 1 and version 2.

**Comment by dasongli1** [comment]
1. Yes, In the joint training, version 1 uses two U-Nets and version 2 uses only one.
2. You can change the model of whole network (remove other parameters) to obtain a partial network (prior_upsampling or ConvEncoder). Then load the partial network weight from the whole network weight (model.load_state_dict(*, strict=False)). 
3. SPADEResnetBlock((2**i) * wf, (2**i) * wf, norm_G, label_nc=(2**i) * wf)) is Spatial Adaptive Modulation. 
4. We use 8 V100 gpus. Stage2 requires 7 days and Stage1 requires 4 days.
