### ISSUE TITLE
About details

### ISSUE THREAD

**Issue by Ideal-Bushgorman** [dasongli1/Learning_degradation#8]
I would be appreciate it if you can help me make clear of some details.
Here are some of my inferences：
1. As you have mentioned, Version 1 need high GPU memory. According to your code, I think the reason is that the deblurring branch in version 1 is more complicated because its framwork is similar to HINet which has two stages and the network is simpler in Version2's(Training version 2's Learning degradation in joint training of reblurring and deblurring).
2. It seems the code just saved the whole network, which means I have to save the subnetworks manually(self.prior_upsampling = prior_upsampling(),self.net_prior = ConvEncoder()) . The second one is about Enconder, the first one is to upsample the features generated by encoder.
3. In fig.2 of the paper, the network uses SAM module to integrate features, but in the code, the network uses SPADEResnetBlock to integrate features. (Class HINet, self.ad1_list.append(SPADEResnetBlock((2**i) * wf, (2**i) * wf, norm_G, label_nc=(2**i) * wf))). It confused me a lot.
4. What type of GPU do you use and how long have you been training

**Comment by dasongli1** [comment]
1. Yes, In the joint training, version 1 uses two U-Nets and version 2 uses only one.
2. You can change the model of whole network (remove other parameters) to obtain a partial network (prior_upsampling or ConvEncoder). Then load the partial network weight from the whole network weight (model.load_state_dict(*, strict=False)).
3. SPADEResnetBlock((2i) * wf, (2i) * wf, norm_G, label_nc=(2**i) * wf)) is Spatial Adaptive Modulation.
4. We use 8 V100 gpus. Stage2 requires 7 days and Stage1 requires 4 days.

**Comment by Ideal-Bushgorman** [comment]
I'm more than grateful for your detailed explanation!!!


19121922&nbsp;李想
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dasongli1/Learning_degradation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月26日(星期一) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dasongli1/Learning_degradation] About details (Issue #8)





  
Yes, In the joint training, version 1 uses two U-Nets and version 2 uses only one.
 
You can change the model of whole network (remove other parameters) to obtain a partial network (prior_upsampling or ConvEncoder). Then load the partial network weight from the whole network weight (model.load_state_dict(*, strict=False)).
 
SPADEResnetBlock((2i) * wf, (2i) * wf, norm_G, label_nc=(2**i) * wf)) is Spatial Adaptive Modulation.
 
We use 8 V100 gpus. Stage2 requires 7 days and Stage1 requires 4 days.
