### ISSUE TITLE
The code implementation is inconsistent with the paper

### ISSUE THREAD

**Issue by xmyhhh** [dasongli1/Learning_degradation#9]
First of all, thank you for sharing the code！So that I can learn details in your work

After reading the paper and code, I found that the code implementation is quite different from the description in the paper

this is the arch from paper
<img width="644" alt="image" src="https://user-images.githubusercontent.com/31955947/215997166-b7f44f08-3838-40ff-a512-707ff09b5bf0.png">

and this is the arch i draw (msdi_arch.py)
<img width="1644" alt="image" src="https://user-images.githubusercontent.com/31955947/215996696-92cb55c2-abce-4779-95cc-0ff579326f9e.png">

The biggest difference is：The using of module “ SAM”

> in paper page 9： "we utilize a spatially adaptive modulation (SAM) module to modulate the skip-connection feature fi at scale i"
> in code : Only one sam module is used (e.g. msdi_arch.py line 146) 

> in paper Fig2:  Degradation Representation only as input to SAM module
> in code: msdi_arch.py line 195, latent_list is the input of ad1_list[i], which is not SAM module 

My question is: Is there any special reason to do so? or my understanding is wrong? 

thanks again！

**Comment by xmyhhh** [comment]
by the way, i think the Fig2 is drawn incorrectly
<img width="814" alt="c1567fbeebf24323d9a9d5833d148c6" src="https://user-images.githubusercontent.com/31955947/216002489-8dcb9d1d-9391-45ba-8e6a-24a00532828b.png">

Is the arrow reversed? After all, the SAM module is a two-input and two-output module, isn't it?

**Comment by dasongli1** [comment]
Thank you for your attention on this paper.
Q1: We use multiple scales SAM in U-Net. (msdi_arch.py Line 194)
Q2: latent list is obtain by a series of upsampling blocks. which is in SAM blocks. (msdi_arch.py Line 61) 
Q3: I think the arrow direction should be reversed. we will upload a new graph with correct arrow. Thank you for your kindness.
